<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>小额贷款 - 判别日志界面</title>
</head>
<body>
	<h1>小额贷款信用判别日志</h1>
	<table border='0'>
		<tr>
			<td>企业名称</td>
			<td>_________</td>
			<td>性质
			</th>
			<td>_________</td>
			<td>测定日期</td>
			<td>_________</td>
		</tr>
	</table>
	<table border='1'>
		<tr>
			<th>序号</th>
			<th>指标</th>
			<th>指标得分</th>
			<th>指标权重</th>
			<th>权重得分</th>
		</tr>
		<tr>
			<td>1</td>
			<td>名称地址规范</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>2</td>
			<td>注册资本</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>3</td>
			<td>行业景气</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>4</td>
			<td>组织/所有权结构</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>5</td>
			<td>有效经营年限</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>6</td>
			<td>三月内财务报表</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>7</td>
			<td>其他关键财务</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>8</td>
			<td>产品生产特征</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>9</td>
			<td>产品品质特征</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>10</td>
			<td>产品市场需求</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>11</td>
			<td>产品竞争特征</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>12</td>
			<td>产品用户特征</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>13</td>
			<td>账款催收记录</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>14</td>
			<td>销售变现天数</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>15</td>
			<td>付款异常</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>16</td>
			<td>同行信用记录</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>17</td>
			<td>主管个人信用</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<th>18</th>
			<th>合计</th>
			<th>——</th>
			<th></th>
			<th></th>
		</tr>
	</table>
</body>



</html>